### ISSUE TITLE
Read HTCondor Wiki Timeline RSS

### ISSUE THREAD

**Issue by JoshKarpel** [JoshKarpel/chtc-bot#33]
It turns out that the wiki timeline has an RSS feed at https://htcondor-wiki.cs.wisc.edu/index.cgi/timeline . 

We could, if we were brave enough, make something like the GitHub bot that sends these updates to a channel on Slack, maybe even #flightworthy. I suspect people would get annoyed at the rate of messages, although I like the idea of trying to keep everyone updated in these quarantimes.

More generally, it seems like we could have a new class of behavior for "post messages based on a feed in a specified channel".

**Comment by toddlmiller** [comment]
If we had stable (external) state, the bot could send individuals their updates filtered appropriately (see the check boxes at the bottom of the timeline) and batched appropriately (the bot will send up all of the updates from the 5PM to 9AM at 9AM, and then  the last hour's updates once an hour).

I say this requires stable storage not just because of summary timers, but because the bot would need to remember individual user preferences.

This would, of course, be opt in, perhaps via a slash command.  (/updates?)  You could use this as an excuse to learn about Slack's bot interactivity stuff (and using Block Kit): user types /updates, bot responds with a little UI with the options.

**Comment by JoshKarpel** [comment]
I like the idea of making it configurable!

External state is not toooooo hard. It's relatively easy to hook Flask up to a database via sqlalchemy and flask-sqlalchemcy. Heroku provides free postgres instances.

**Comment by toddlmiller** [comment]
I was more thinking in reference to #7; I assume it's silly to have more than one state mechanism.

**Comment by JoshKarpel** [comment]
Unfortunately it's not; Redis is only really good for ephemeral state that looks like key/value pairs. I think for storing user preferences we would want a real database.
